### ISSUE TITLE
"date" type kills the processing

### ISSUE THREAD

**Issue by adam-ah** [Daij-Djan/xsd2cocoa#1]
A line like this:
<xs:attribute name="VALUE" type="date">/xs:attribute

Would cause an assert failure:

Assertion failed: (retType), function -[XSDschema typeForName:], file /Users/cba-user/Downloads/xsd2cocoa-master/framework/XSDschema.m, line 340.

Adding full XSD sample here: http://pastebin.com/jkdAPuC9

**Comment by Daij-Djan** [comment]
sorry I think github messed up the line of xsd you wanted to type?
anyway, I did fix a serious bug with dates but before pushing it, id like to see your issue again :)

**Comment by Daij-Djan** [comment]
1.5.1 parses the XSD you attached. I added date & time types. Please verify

**Comment by Daij-Djan** [comment]
@adam-ho  plz verify

**Comment by Daij-Djan** [comment]
dates work
