### ISSUE TITLE
Namespaced schemas don't generate any output

### ISSUE THREAD

**Issue by adam-ah** [Daij-Djan/xsd2cocoa#2]
An XSD with a header like this:

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="GSP">
        xs:complexType
...

Would generate empty output.

Reason: XSDSchema.m, ln 78 wouldn't pick up any complex types because of the incorrect XPath selector:
NSArray\* ctNodes = [node nodesForXPath: @"/schema/complexType" error: error];

Adding full XSD sample here: http://pastebin.com/jkdAPuC9

**Comment by Daij-Djan** [comment]
sorry I think github messed up the line of xsd you wanted to type?
namespacing works fine afaics, id like to see your issue again :)

**Comment by MarekR22** [comment]
Hi, I've accoutered exactly same issue and made quick fix for this issue. 
It is not perfect solution at least it shows what is the problem: 
https://github.com/MarekR22/xsd2cocoa/commit/ff8e686c122dd80adb751d0419d4a8803cac9bc5

**Comment by Daij-Djan** [comment]
Hi, I just pushed version 1.5 with swift support and it should incorporate a fix inspired by your workaround. - could you please check this again?

**Comment by MarekR22** [comment]
Hi I test it and it works perfectly, thanks.

Wen I've tried fix it myself, I had problems to pass tests.
Can you tell me what is current state of test? Should they all pass? Or do you have some failing test?
On my machine test are failing on master branch (I have enabled Xcode command line tools).

**Comment by Daij-Djan** [comment]
on 10.10 all tests are green and all demo apps work :/
If you’re on 10.11 that’d explain a lot :) ill have to look into that in the next days (see #6)

cheers
Dominik

**Comment by Daij-Djan** [comment]
ok I fixed the unit tests for 10.11. the problem was that I used the /usr/include dir directly and on 10.11 this isn't there by default. They should be all green now.  (they are here ;)
the demos work as well

**Comment by Daij-Djan** [comment]
@adam-ho  plz verify

**Comment by Daij-Djan** [comment]
im on 10.11 and it works ;)
