### ISSUE TITLE
NSNumberFormatter and german local

### ISSUE THREAD

**Issue by HighKo** [Daij-Djan/xsd2cocoa#9]
```
NSNumberFormatter* decFormatter = [[NSNumberFormatter alloc] init]; 
decFormatter.decimalSeparator = @".";
decFormatter.numberStyle = NSNumberFormatterDecimalStyle;
```

The initializiation of the NSNumberFormatter is missing the groupingSeperator.
This leads to the same grouping and decimalSeperator for german (DE) local. (Both are ".")

This leads to strange behavior when interpreting numbers.
@"1.00" will be interpreted as 1
@"1.000" will be interpreted as 1000

**Comment by Daij-Djan** [comment]
setting the separator at all was a mistake in the old code. I refactored all the formatters to use the enUSPOSIXLocale. That fixes this issue IMO

**Comment by Daij-Djan** [comment]
ill upload a version tonight (CET)

**Comment by HighKo** [comment]
Thanks for the fix. My unit tests are happy again.
